apiVersion: v1
kind: Pod
metadata:
  name: plane-backup-shell
  namespace: plane-ce
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: localhost:32000/plane-backup:latest
      command: ["sleep", "3600"]
      envFrom:
        - secretRef:
            name: plane-backup-restic-creds
        - secretRef:
            name: plane-app-pgdb-secrets
        - secretRef:
            name: plane-app-doc-store-secrets
